name: Lint

env:
  NODE_VERSION: 20

on:
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm install

      - name: Run linter
        run: npm run lint
